[package]
name = "aoc-2015"
version = "0.1.0"
authors = ["shardamaka <mariusalexandrutache@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day1"
path = "src/day1/main.rs"